#!/usr/bin/env node
/**
 * Self-hosts the two typefaces so the site never waits on a third-party CDN
 * and keeps working offline. Only the latin + vietnamese subsets are kept —
 * the whole family would be ~6× the weight for glyphs we never set.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outDir = path.join(root, 'public/fonts')
fs.mkdirSync(outDir, { recursive: true })

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36'
const KEEP = new Set(['latin', 'latin-ext', 'vietnamese'])
const url = 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300&family=Be+Vietnam+Pro:wght@100;200;300;400&display=swap'

const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text()

let subset = null
const faces = []
for (const line of css.split('\n')) {
  const c = /\/\*\s*([a-z-]+)\s*\*\//.exec(line)
  if (c) { subset = c[1]; continue }
  const block = /@font-face\s*\{([^}]+)\}/s
  faces.push({ subset, line })
}

// Re-parse properly: split on @font-face blocks, tracking the preceding comment.
const out = []
const re = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/gs
let m
while ((m = re.exec(css))) {
  const [, sub, face] = m
  if (!KEEP.has(sub)) continue
  const family = /font-family:\s*'([^']+)'/.exec(face)[1]
  const weight = /font-weight:\s*(\d+)/.exec(face)[1]
  const style = /font-style:\s*(\w+)/.exec(face)[1]
  const src = /url\((https:[^)]+)\)/.exec(face)[1]
  const name = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}${style === 'italic' ? 'i' : ''}-${sub}.woff2`
  const buf = Buffer.from(await (await fetch(src)).arrayBuffer())
  fs.writeFileSync(path.join(outDir, name), buf)
  const range = /unicode-range:\s*([^;]+);/.exec(face)[1]
  out.push(`@font-face {
  font-family: '${family}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url('/fonts/${name}') format('woff2');
  unicode-range: ${range};
}`)
  console.log(`  ${name}  ${(buf.length / 1024).toFixed(1)}kb`)
}

fs.writeFileSync(path.join(root, 'src/styles/fonts.css'), `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n${out.join('\n\n')}\n`)
console.log(`\n→ src/styles/fonts.css (${out.length} faces)`)
