#!/usr/bin/env node
/**
 * Self-hosts the two typefaces so the site never waits on a third-party CDN
 * and keeps working offline. Only the latin + vietnamese subsets are kept —
 * the whole family would be ~6× the weight for glyphs we never set.
 *
 * The files land in src/fonts, not public/fonts, and fonts.css points at them
 * with a relative path. That is not a detail: a rule written as `/fonts/x.woff2`
 * asks for a path one level above the site on GitHub Pages, every face 404s,
 * and the whole thing quietly renders in Times New Roman. Vite resolves the
 * relative form itself and rewrites it with the right base at build time.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outDir = path.join(root, 'src/fonts')
fs.rmSync(outDir, { recursive: true, force: true })
fs.mkdirSync(outDir, { recursive: true })

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36'
const KEEP = new Set(['latin', 'latin-ext', 'vietnamese'])
const url = 'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;1,400&family=Be+Vietnam+Pro:wght@200;300;400;500&display=swap'

const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text()

const out = []
/** Which families actually came back with a Vietnamese cut — see the check below. */
const vietnamese = new Set()
const families = new Set()

const re = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/gs
let m
while ((m = re.exec(css))) {
  const [, sub, face] = m
  if (!KEEP.has(sub)) continue
  const family = /font-family:\s*'([^']+)'/.exec(face)[1]
  const weight = /font-weight:\s*(\d+)/.exec(face)[1]
  const style = /font-style:\s*(\w+)/.exec(face)[1]
  const src = /url\((https:[^)]+)\)/.exec(face)[1]
  const range = /unicode-range:\s*([^;]+);/.exec(face)[1]
  const name = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}${style === 'italic' ? 'i' : ''}-${sub}.woff2`

  families.add(family)
  // A "vietnamese" block is only served for a family that really carries the
  // diacritics. Checking the range as well, because a block that did not cover
  // U+1EA0–1EF9 would leave every ạ ế ữ ỹ to a fallback face.
  if (sub === 'vietnamese' && /1EA0-1EF9/i.test(range) && /01A0-01A1/i.test(range)) vietnamese.add(family)

  const buf = Buffer.from(await (await fetch(src)).arrayBuffer())
  fs.writeFileSync(path.join(outDir, name), buf)
  out.push(`@font-face {
  font-family: '${family}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url('../fonts/${name}') format('woff2');
  unicode-range: ${range};
}`)
  console.log(`  ${name}  ${(buf.length / 1024).toFixed(1)}kb`)
}

const missing = [...families].filter((f) => !vietnamese.has(f))
if (missing.length) {
  console.error(`\n  ! Không có bản chữ tiếng Việt cho: ${missing.join(', ')}`)
  console.error(`    Font này sẽ thiếu dấu — chọn font khác.\n`)
  process.exit(1)
}

fs.writeFileSync(path.join(root, 'src/styles/fonts.css'), `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n${out.join('\n\n')}\n`)
console.log(`\n→ src/styles/fonts.css (${out.length} faces, ${[...families].join(' + ')} — đủ dấu tiếng Việt)`)
